### ISSUE TITLE
Does the "Hot-Deploy" section in the README need to be updated?

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-support-tools#13]
Specifically you are using your javascript extension for more than just log inspection. I suspect some or your JMX magic will likely not work with a hot deployment? I have not actually installed this add-on yet, so just guessing from looking through the code a bit.

**Comment by AntonioSoler** [comment]
Hi,
The only two things that would not work on a hot deployment are the Tail Log script that relies on my custom log4Appender and the JMX settings inspector to revert persisted values.
The first one is already mentioned on the readme but not the second, I will do this asap.
chers

**Comment by AntonioSoler** [comment]
solved:  a1b8fe2b5eaf5972b3e0e040d01e6b5e70c085fc
