### ISSUE TITLE
log4j.properties overwrites default file layout

### ISSUE THREAD

**Issue by miguel-rodriguez** [Alfresco/alfresco-support-tools#14]
The log4j.properties provided in the module changes the default layout pattern. It should be like this:

log4j.appender.File.layout.ConversionPattern=%d{yyyy-MM-dd} %d{ABSOLUTE} %-5p [%c] %m%n

to include the year-month-day

**Comment by AntonioSoler** [comment]
Log4j properties file updated:

https://github.com/Alfresco/alfresco-support-tools/commit/a7606e771642340524f0acfa9d480ef6f3666caf
