### ISSUE TITLE
Expression user.properties.email is undefined on line 9

### ISSUE THREAD

**Issue by lcabaceira** [Alfresco/alfresco-support-tools#15]
Hi, i've installed the latest version of support-tools and i've left the browser session open and this morning my logs were filled with the following stacktraces.

java backtrace for programmers:
----------
freemarker.core.InvalidReferenceException: Expression user.properties.email is undefined on line 9, column 23 in org/alfresco/enterprise/repository/admin/support-tools/admin-activesessions-updateusers.post.json.ftl.
	at freemarker.core.TemplateObject.assertNonNull(TemplateObject.java:125)
	at freemarker.core.Expression.getStringValue(Expression.java:118)
	at freemarker.core.Expression.getStringValue(Expression.java:93)
	at freemarker.core.StringBuiltins$StringBuiltIn._getAsTemplateModel(StringBuiltins.java:71)
	at freemarker.core.Expression.getAsTemplateModel(Expression.java:89)
	at freemarker.core.ListLiteral.getModelList(ListLiteral.java:119)
	at freemarker.core.MethodCall._getAsTemplateModel(MethodCall.java:91)

Can you advice on a work-arround to prevent the this errors on the logs ?

**Comment by lcabaceira** [comment]
I think i know what the problem can be and you can fix it easy on the code. On the active sessions support-tools page the logged users are displayed and their emails is also displayed. When a user does not have an email on the system we can be getting this error. If this is not the problem, it may as well be that the error is showing  when there are no active sessions. Just a couple of thoughts, i want to leave this tools installed on my customer, but i cannot be filling their logs with errors related with the tool.

I'm available to help to troubleshoot and fix this problem.
Cheers,
Luis

**Comment by AntonioSoler** [comment]
I've changed that line 9 in org/alfresco/enterprise/repository/admin/support-tools/admin-activesessions-updateusers.post.json.ftl :
  "email" : "${(user.properties.email?html)!' '}

to use the http://freemarker.org/docs/dgui_template_exp.html#dgui_template_exp_missing_default

that will prevent the error on missing fields, check update https://github.com/Alfresco/alfresco-support-tools/commit/aeb8924b0545cf96c85687a62443be108324495f
you can modify this manually in your current installation or generate a snapshot version with the github source
