### ISSUE TITLE
Active sessions page fails when "user"-object is missing

### ISSUE THREAD

**Issue by marsv024** [Alfresco/alfresco-support-tools#16]
The js-controller for active sessions for some reason at some points return one or more null user objects. This results in an exception in the ftl.

The solution would be to check if the user object is populated in the ftl before trying to render it. I'm attaching a suggested solution.

**Comment by AntonioSoler** [comment]
tested it and the solution looks good to me

**Comment by AntonioSoler** [comment]
pull request merged
