### ISSUE TITLE
Log4j Settings - admin-log-settings

### ISSUE THREAD

**Issue by walstib** [Alfresco/alfresco-support-tools#18]
I want to enable the "Tail Share Log" feature

If I click on that button, a pop-up appears and states the need for 7 additional entries in the log4j.properties file and I must copy jmxlogger-log4j-0.1.0-AlfrescoPatched.jar ..alfresco/lib to ..share/lib

When deploying to EE 5.0.2.1 via unattended setup, the jmxlogger-log4j-0.1.0-AlfrescoPatched.jar is non-existent in the specified source directory. 

I explode the amp to find the file is named log4j-patched-1.0-AlfrescoPatched.jar.  Not know how the .jar file will be called, I copy it to its intended home
[tomcat]/webapps/alfresco/WEB-INF/lib/ as log4j-patched-1.0-AlfrescoPatched.jar and jmxlogger-log4j-0.1.0-AlfrescoPatched.jar and then into [tomcat]/webapps/share/WEB-INF/lib/ , 

restart alfresco and now the "Tail Share Log" feature works.

Could you get this sorted and fixed?  Maybe call the JAR something like:
alfresco-support-tools-1.8-jmxlogger.jar

**Comment by AntonioSoler** [comment]
Hi, sorry for the delay on this, You are right, since the Mavenization of the tool the file is called 
log4j-patched-1.0-AlfrescoPatched.jar

**Comment by AntonioSoler** [comment]
fixed
