### ISSUE TITLE
Filtered logging for a specific admin console page

### ISSUE THREAD

**Issue by esplinr** [Alfresco/alfresco-support-tools#24]
Alfresco's SAML module does a lot of validation in the log, and we want to expose the logging specific to that module to the administrator in the Admin console (see private issue SAML-221)

It would be great for support tools to provide a component that can be embedded into an Admin console page which displays logs filtered according to the subsystem on that page.

**Comment by esplinr** [comment]
Note from research by @ahmedowian:
> In admin-log-settings.inc.ftl we see
> `label="Tail Alfresco Log" onclick= "Admin.showDialog('${url.serviceContext}/enterprise/admin/admin-log-settings-tail?context=Alfresco');`
> which we could use in SAML to show the repository log.

Note from our discussion with @AntonioSoler on this topic:

> The way it works in my use case is this:
> With the log4j jmx Appender on the class-path you can define on log4j another appender dynamically. In the appender configuration I select the settings that will create a new Mbean called "log emitter". That log emitter caches the last 3000 chars from the log, the cache size of the emitter is configurable via Mbean method "setTailSize".
> You could easy add more log emitters (like the sample one I put for share) using the same approach, and the button visiilty on the ftl could be based on the pressence of the log emitter and certain modules, to filter the log only for a certain batch of classes may require more work on the log4j jmx Appender or post processing the whole tail.
> One thing that also could be necessary is to ensure that all the classes are at the required debug/trace level.

**Comment by AntonioSoler** [comment]
I've added the source code of the JMXLogger in the /resources folder for the sake of completion.

**Comment by AntonioSoler** [comment]
closing this as Ray submitted a solution for this in  	5c37dc0
