### ISSUE TITLE
log4j Issues

### ISSUE THREAD

**Issue by mtwallach** [Alfresco/alfresco-support-tools#34]
Installed Support Tools 1.11. Have tomcat config to log to /var/log/tomcat-alfresco/alfresco.log. 
(-Dlogfilename=/var/log/tomcat-alfresco/alfresco.log)
When Alfresco starts it is logging to /var/log/tomcat-alfresco/alfresco.log but then switches to logging to /usr/share/tomcat (it is using Support Tools log4j) Is there a way to have it continue to log to /var/log/tomcat-alfresco/alfresco.log (short of setting that in the support-tools log4j)?

**Comment by AntonioSoler** [comment]
This is because we set the main output in the module log4j file to redirect the output to the JMXlogger appender so I can tail the log from JMX.

You could easily move the settings from the module log4j file to the main log4j file and do your adjustments there .
