### ISSUE TITLE
Support Tools log4j.properties file is overriding all other log settings

### ISSUE THREAD

**Issue by itsnotify** [Alfresco/alfresco-support-tools#6]
Hi,

We recently upgraded our Alfresco instance to Alfresco 4.2.2 and upgraded to support tools 1.5.

After doing so we had the error:
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: alfresco.log (Permission denied)

After a some checking we found the cause was the Alfresco Support tools amp. If we updated it's log4j.properties file to point to the correct location logging worked fine otherwise it's config overrides all other log4j files and even seems to replace what's configured in the DB. I.e. We set the file correctly via JMX, restarted the config was lost again.

A possible bigger issue... We tried removing the Support tools amp completely, recreating the WAR file from scratch (with clean sources). Deploying this to the system (even after cleaning tomcat work and temp folders) resulted in something triggering the Java debugger in graphical mode. We then had headless errors and the applications failed to start completely. Adding the Support tools amp back in resolves the issue.

So our workaround at the moment has been to update the support tools log4j.properties file but there's clearly one or two issues with this latest version.

**Comment by igorbga** [comment]
I think that the JMX appender idea sounds great. Loosing some of the startup logs shouldn't be such a big deal as long as it is clearly documented, after all in order to start the service you probably did connect to the server so you can check the bootstrap log there.

**Comment by AntonioSoler** [comment]
On the 1.7 version I no longer overwrite the original LOG4J, I will close this once the version 1.7 is finished.

**Comment by AntonioSoler** [comment]
this is resolved now in 1.7.1
