### ISSUE TITLE
Error processing persisted values when clicking on JMX settings page

### ISSUE THREAD

**Issue by CesarCapillas** [Alfresco/alfresco-support-tools#9]
Hi, first of all congrats for the module, it is very useful.
I am obtaining this error in Alfresco 4.2.4 EE when clicking in JMX Settings page of the module every time I click on the link. It results on a very large ERROR log. Then all seems to work but...

<pre>
2015-02-25 19:21:22,187  ERROR [util.jscript.SupportToolsApi] [http-apr-8080-exec-8] Error processing Persisted Values  │
  │        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
</pre>

Any idea ?

Regards.

--C.

**Comment by AntonioSoler** [comment]
Hi Cesar,
Are you getting this error using the 1.6 release or are you building the amp yourself with maven?
I think that Rich Mckinght already resolved this error when he did the refactor of this webscript on the 1.7 snapshot.

**Comment by CesarCapillas** [comment]
Hi Antonio:

Thanks for the feedback. 
We are using the current pom.xml of the project that points to 1.7 Snapshot (in version token) but later the tag token is flagged as (1.6.1). I am not sure about the version, it was compiled two weeks ago.

Regards.

--C.

**Comment by CesarCapillas** [comment]
Hi again:

One minor thing to take into account is that we did not find alfresco 4.2.4 version in maven, only 4.2.3.3, so it was compiled for this.

Regards.

--C.

**Comment by CesarCapillas** [comment]
Idem with 4.2.1 EE.

Thanks in advance.

--C.

**Comment by AntonioSoler** [comment]
Bug fixed in b8beffc484d2b4d56b8fe7c171fdb5af3dfda79a

**Comment by CesarCapillas** [comment]
Checked in Alfresco 4.2.4.

Thank you very much Antonio.

--C.
